export interface TpObjectType {
    id: number;
    name: string;
    prefix: string;
    type: string;
    enable: number;
    autogenerated_name: number;
    editable_name: number;
    access_code: string;
    slug: string;
    public: number;
    show_image: number;
    show_description: number;
    description: string | null;
}
